apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: todo-app-rules
  namespace: todo-app
spec:
  groups:
  - name: node.rules
    rules:
    - alert: NodeNotReady
      expr: kube_node_status_condition{condition="Ready",status="true"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Node not ready"
        description: "One or more nodes are not Ready for more than 5 minutes."
  - name: pod.rules
    rules:
    - alert: HighCPUUsage
      expr: sum by(pod) (rate(container_cpu_usage_seconds_total{container!="",image!=""}[2m])) > 0.5
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on pod"
        description: "Pod is using over 50% CPU for 2 minutes."
    - alert: PodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarting frequently"
        description: "A pod has restarted more than 3 times in 5 minutes."
