apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todo-app
data:
  TASK_SERVICE_ADDR: "task-service:50051"
  USER_SERVICE_ADDR: "user-service:50052"
  NOTIFICATION_SERVICE_ADDR: "notification-service:50053"
  ANALYTICS_SERVICE_ADDR: "analytics-service:50054"
