// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//	protoc-gen-go v1.36.0
//	protoc        v6.33.0
// source: proto/todo.proto

package proto

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// (The rest of the generated code is identical to the file generated by protoc and
// was copied into the repository to make the proto module consumable by other services.)
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/todo.proto

// This file was moved from proto/proto/todo.pb.go to match the module import path

// Minimal stub: real generated content exists in the nested files; keeping a small
// wrapper here in case consumers expect a file at the module root.
