# prometheus-stack-values.yaml
# Minimal values: Enables core components.

prometheus:
  enabled: true

grafana:
  enabled: true
  

alertmanager:
  enabled: true

# Prometheus Operator (enabled by default) handles PrometheusRule resources.
prometheusOperator:
  enabled: true