# loki-values.yaml
# Grafana Loki configuration with 2-day retention policy

loki:
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1
  
  storage:
    type: filesystem
  
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  limits_config:
    retention_period: 48h  # 2 days retention
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    max_query_parallelism: 32
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
    per_stream_rate_limit: 5MB
    per_stream_rate_limit_burst: 15MB
  
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    working_directory: /var/loki/compactor

  querier:
    max_concurrent: 4

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Enable monitoring
monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
  serviceMonitor:
    enabled: true
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

# Gateway configuration
gateway:
  enabled: true
  replicas: 1
  service:
    type: ClusterIP
    port: 80

# Test configuration
test:
  enabled: false

# Backend configuration
backend:
  replicas: 0

# Read configuration  
read:
  replicas: 0

# Write configuration
write:
  replicas: 0