# tempo-values.yaml
# tempo: # This top-level key might not be needed depending on chart version
# It's common for Tempo values to start directly with components like 'compactor'

compactor:
  compaction:
    # Use this parameter for block retention
    block_retention: 48h # 2-day retention

# Enable OpenTelemetry receiver endpoints (required for apps to send traces)
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true