apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
  # NOTE: The full URI has been removed. Keep only credentials in the Secret
  # Build the full connection string in the Pod using the ConfigMap FQDN + these credentials.
